# Generated by Django 3.0.5 on 2020-04-25 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0002_game_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='is_over',
        ),
    ]
