# Generated by Django 3.0.5 on 2020-04-26 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0004_auto_20200426_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='roll_four',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='roll_one',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='roll_three',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='frame',
            name='roll_two',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_app.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_app.Player'),
        ),
        migrations.DeleteModel(
            name='Roll',
        ),
    ]
