# Generated by Django 3.0.5 on 2020-04-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0010_frame_extra_frame_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='roll_three',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
