# Generated by Django 3.0.5 on 2020-04-24 22:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('in_progress', models.BooleanField(default=True)),
                ('is_over', models.BooleanField(default=False)),
                ('final_score', models.IntegerField(default=0)),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='scoring_app.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Frame',
            fields=[
                ('frame_id', models.AutoField(primary_key=True, serialize=False)),
                ('frame_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('roll_one', models.IntegerField(default=0)),
                ('roll_two', models.IntegerField(default=0)),
                ('roll_three', models.IntegerField(default=0)),
                ('roll_four', models.IntegerField(default=0)),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='scoring_app.Game')),
            ],
        ),
    ]
