# Generated by Django 3.0.5 on 2020-04-24 15:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_no',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
