# Generated by Django 3.0.5 on 2020-04-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0002_auto_20200424_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='roll_one',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='frame',
            name='roll_two',
            field=models.IntegerField(blank=True),
        ),
    ]
