# Generated by Django 3.0.5 on 2020-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0004_auto_20200424_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='roll_one',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='frame',
            name='roll_two',
            field=models.IntegerField(default=0),
        ),
    ]
