# Generated by Django 3.0.5 on 2020-04-24 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0005_auto_20200424_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frame',
            name='frame_no',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
