# Generated by Django 3.0.5 on 2020-04-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0007_remove_game_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
