# Generated by Django 3.0.5 on 2020-04-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0009_remove_frame_roll_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='extra_frame_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
