# Generated by Django 3.0.5 on 2020-04-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0010_auto_20200424_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frame',
            name='frame_no',
        ),
        migrations.AlterField(
            model_name='frame',
            name='game_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='scoring_app.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='scoring_app.Player'),
        ),
    ]
