# Generated by Django 3.0.5 on 2020-04-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_app', '0011_auto_20200428_0624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='player_name',
            new_name='player_id',
        ),
    ]
